seata:
  data-source-proxy-mode: AT
server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
    host: 192.168.100.131 # 修改为你自己的虚拟机IP地址
    pw: 123 # 修改为docker中的MySQL密码
    port: 3307