server:
  port: 8081
feign:
  okhttp:
    enabled: true
hm:
  db:
    host: 192.168.100.131 # 修改为你自己的虚拟机IP地址
    pw: 123 # 修改为docker中的MySQL密码
    database: hm-cart
    port: 3307
  swagger:
    title: "黑马商城购物车管理接口文档"
    desc: "黑马商城购物车管理接口文档"
    package: com.hmall.cart.controller