seata:
  data-source-proxy-mode: AT
server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    host: 192.168.100.131 # 修改为你自己的虚拟机IP地址
    pw: 123 # 修改为docker中的MySQL密码
    database: hm-item
    port: 3307
  swagger:
    title: "商品管理接口文档"
    desc: "商品管理接口文档"
    package: com.hmall.item.controller